server:
  port: 8080
  servlet:
    context-path: /springkit

spring:
  datasource:
    type: org.h2.jdbcx.JdbcDataSource
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;IGNORECASE=TRUE;
  h2:
    console:
      enable: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
      
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true